image: java



cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

tests_and_report:
  tags:
    - iWOCS
  stage: test
  script: 
    - "./mvnw $MAVEN_OPTS clean install -B"
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
  coverage: '\d+.\d+ \% covered'
